import os
from waflib import Logs

top = '.'
try:
    out
except NameError:
    # out not defined
    out = 'build'

def options(conf):
    pass

def configure(conf):
    Logs.info("Cdb: Configuring...")

def makeInstall(ctx):
    from IasWafBuildTools.Installer import Installer
    installer = Installer(ctx)
    ctx.add_to_group(installer)

def makeBuild(bld, env):
    '''
    Make the build

    :param bld: The waf buyild context
    :param env: The Waf environment
    :return:
    '''
    Logs.info("Building %s", bld.path.abspath())

    #
    # get Jars from extTools
    #
    from IasWafBuildTools.JarTasks import getJarsFromExtTools
    copyExtJarTask = getJarsFromExtTools(env)
    bld.add_to_group(copyExtJarTask)

    #
    # get jars from ZIP c3p0
    #
    zipFileName="c3p0-0.9.5.2.bin.zip"
    jarsInZip = [
        "c3p0-0.9.5.2.jar",
        "c3p0-oracle-thin-extras-0.9.5.2.jar",
        "mchange-commons-java-0.2.11.jar"
    ]

    from IasWafBuildTools.JarTasks import jarsFromZip
    jarsFromZipTask = jarsFromZip(zipFileName, jarsInZip, env)
    bld.add_to_group(jarsFromZipTask)

    #
    # Get jar from tar
    #
    tarFileName="hibernate-search-5.5.5.Final-dist.tar.gz"
    jars = [
        "antlr-2.7.7.jar",
        "hibernate-commons-annotations-5.0.1.Final.jar",
        "jboss-logging-3.3.0.Final.jar",
        "dom4j-1.6.1.jar",
        "hibernate-core-5.0.11.Final.jar",
        "javassist-3.18.1-GA.jar",
        "lucene-core-5.3.1.jar",
        "xml-apis-1.3.03.jar",
        "hibernate-jpa-2.1-api-1.0.0.Final.jar",
        "jboss-transaction-api_1.2_spec-1.0.0.Final.jar"
    ]

    from IasWafBuildTools.JarTasks import jarsFromTar
    getJarsFromTarTask = jarsFromTar(tarFileName, jars, env)
    bld.add_to_group(getJarsFromTarTask)

    #
    # Python modules
    #
    from IasWafBuildTools.PythonBuilder import buildPythonModules
    bldPyMods = buildPythonModules(env)
    bld.add_to_group(bldPyMods)

    #
    # Java sources
    #
    from IasWafBuildTools.JavaBuilder import buildJava
    javaBuilder = buildJava(env)
    javaBuilder.set_run_after(getJarsFromTarTask)
    bld.add_to_group(javaBuilder)

    #
    # Build the jar
    #
    from IasWafBuildTools.JarTasks import buildJar
    jar_builder = buildJar(env, "iasCdb.jar")
    jar_builder.set_run_after(javaBuilder)
    bld.add_to_group(jar_builder)

def build(bld):
    bld.load('IasWafBuildTools', tooldir='../WafBuildTools/src/main/python/')
    bld.add_group("Cdb")
    from IasWafBuildTools.Utils import set_env
    env = bld.env.derive()
    set_env(env, bld.path, bld.bldnode)
    env.PREFIX = os.environ['IAS_ROOT']

    if bld.cmd == 'build':
        makeBuild(bld, env)
    elif bld.cmd == 'install':
        makeInstall(bld)
    elif bld.cmd == 'clean':
        Logs.info("Cleaning %s/extTools", bld.bldnode.abspath())
        bld(rule='rm -rf build/*', always=True)
