import os
from waflib import Logs

top = '.'
out = 'build'

def options(conf):
    pass

def configure(conf):
    Logs.info("Configuring Cdb...")

def makeInstall(ctx):
    from IasWafBuildTools.Installer import Installer
    installer = Installer(ctx, ctx.env.DSTNODE, ctx.env.PREFIX)
    installer.install()


def makeBuild(bld):
    #
    # get Jars from extTools
    #
    from IasWafBuildTools.FileTasks import CopyTask
    copyExtJarTask = CopyTask(bld.env, bld.env.SRCEXTTOOLSFOLDER, file_extension=".jar")
    copyExtJarTask.color= 'CYAN'
    bld.add_to_group(copyExtJarTask)

    #
    # get jars from ZIP c3p0
    #
    zipFileName="c3p0-0.9.5.2.bin.zip"

    jarsInZip = [
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("c3p0-0.9.5.2.jar"),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("c3p0-oracle-thin-extras-0.9.5.2.jar"),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("mchange-commons-java-0.2.11.jar")
    ]

    Logs.info("jars to get from ZIP",jarsInZip)

    from IasWafBuildTools.JarTasks import GetJarsFromZip

    jarsFromZipTask = GetJarsFromZip(env=bld.env)
    jarsFromZipTask.color='YELLOW'
    jarsFromZipTask.set_inputs(bld.env.SRCEXTTOOLSFOLDER.find_node(zipFileName))
    jarsFromZipTask.set_outputs(jarsInZip)
    bld.add_to_group(jarsFromZipTask)

    #
    # Get jar from tar
    #
    tarFileName="hibernate-search-5.5.5.Final-dist.tar.gz"
    jars = [
        "antlr-2.7.7.jar",
        "hibernate-commons-annotations-5.0.1.Final.jar",
        "jboss-logging-3.3.0.Final.jar",
        "dom4j-1.6.1.jar",
        "hibernate-core-5.0.11.Final.jar",
        "javassist-3.18.1-GA.jar",
        "lucene-core-5.3.1.jar",
        "xml-apis-1.3.03.jar",
        "hibernate-jpa-2.1-api-1.0.0.Final.jar",
        "jboss-transaction-api_1.2_spec-1.0.0.Final.jar"
    ]

    from IasWafBuildTools.JarTasks import jarsFromTar
    getJarsFromTarTask = jarsFromTar(tarFileName,jars, bld.env)
    getJarsFromTarTask.set_run_after(copyExtJarTask)
    bld.add_to_group(getJarsFromTarTask)

def build(bld):
    bld.load('IasWafBuildTools', tooldir='../WafBuildTools/src/main/python/')
    bld.bldnode=bld.path.make_node('build')
    from IasWafBuildTools.Utils import set_env
    set_env(bld.env,bld.path,bld.bldnode)
    bld.env.PREFIX = os.environ['IAS_ROOT']
    
    if bld.cmd == 'build':
        Logs.info('=====>>> Cdb build...', bld.cmd)
        makeBuild(bld)
    elif bld.cmd == 'install':
        Logs.info('=====>>> Cdb install...',bld.cmd)
        makeInstall(bld)
