package org.eso.ias.supervisor.inttest

import java.nio.file.{FileSystems, Path}
import java.util.{Properties, Collection}
import java.util.concurrent.{CountDownLatch, TimeUnit}
import java.util.concurrent.atomic.AtomicReference

import scala.jdk.CollectionConverters._
import scala.collection.mutable.{ListBuffer, Map=>MutableMap, HashMap}
import scala.util.Random

import ch.qos.logback.classic.Level

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.{BeforeAndAfter, BeforeAndAfterAll}

import org.eso.ias.logging.IASLogger
import org.eso.ias.cdb.CdbReader
import org.eso.ias.cdb.pojos.DasuDao
import org.eso.ias.cdb.structuredtext.StructuredTextReader
import org.eso.ias.dasu.DasuImpl
import org.eso.ias.dasu.publisher.OutputPublisher
import org.eso.ias.dasu.subscriber.{InputSubscriber, KafkaSubscriber}
import org.eso.ias.types._
import org.eso.ias.kafkautils.SimpleKafkaIasiosConsumer.IasioListener
import org.eso.ias.kafkautils.{KafkaHelper, KafkaIasiosProducer, SimpleKafkaIasiosConsumer, SimpleStringProducer}
import org.eso.ias.kafkautils.KafkaStringsConsumer.StreamPosition
import org.eso.ias.supervisor.Supervisor
/**
  * Test provided by CII for ECII-1383 that was about reliability:
    after some iteration the outputs were not produced.
  * 
  * The test runs the supervisor with the DASUs and ASCEs defined in ias-cdb/CDB then
  * sends the inputs and checks the outputs.
  *
  * ECII-1838 
  * 
  * For the description of the test, read integrationTest/ias-cdb/README.md
  */
class SupervisorWithBooleanTFs 
  extends AnyFlatSpec
    with BeforeAndAfterAll
    with BeforeAndAfter {

  /** The logger */
  private val logger = IASLogger.getLogger(this.getClass)
  

  // The IDs of the inputs IASValues
  val idsOfInputs = Set("/device_c/sensor8a", "/device_c/sensor8b")

  // The IDs of the alarms generated by the DASUs
  val idsOfAlarms = Set("/test/alarm8b", "/test/alarm8all", "/test/alarm8any")

  // The IDs of the booleans generated by the DASUs
  val idsOfBools = Set("/vals/hival8a", "/vals/hival8b", "/vals/hival8all", "/vals/hival8any")

  // The IDs of all the IASValues published buy the test in the BSDB
  val idsOfAllIasValues = idsOfInputs ++ idsOfAlarms ++ idsOfBools

  /**
   * The kafka producer used by the test (the supervisor builds its own shared consumer
   */
  val stringProducer = new SimpleStringProducer(KafkaHelper.DEFAULT_BOOTSTRAP_BROKERS,"SupervisorWithBool-Producer")

  /** The serializer to JSON strings */
  val serializer: IasValueStringSerializer = new IasValueJsonSerializer()

  /**
   *  The IASIOs producer submits IASIOs to the kafka topic i.e. to the BSDB:
   *  these IASIOs will be received and processed by the DASU running in the Supervisor
   *
   */
  val iasiosProducer = new KafkaIasiosProducer(
    stringProducer,
    KafkaHelper.IASIOs_TOPIC_NAME,
    serializer)
  iasiosProducer.setUp()
  logger.info("Testing producer started")

  /** All the values read from the BSDB */
  val receivedIasValues = new ListBuffer[IASValue[?]]()

  /** The map of the values read from the BSDB, indexd by IASValue.id */
  val receivedIasValuesMap: MutableMap[String, IASValue[?]] = new HashMap[String, IASValue[?]]()

  /**
   * The kafka consumer gets all the IASIOs written in the IASIO kafka topic
   *
   * It means that it will get the IASIOs submitted by iasiosProducer and those
   * produced by the DASUs running in the Supervisor.
   *
   * To have finer control over the test, we do not setup filters
   * to this consumer
   */
  val iasiosConsumer = new SimpleKafkaIasiosConsumer(
    KafkaHelper.DEFAULT_BOOTSTRAP_BROKERS,
    KafkaHelper.IASIOs_TOPIC_NAME,
    "SupervisorWithBools-Consumer",
    )
  iasiosConsumer.setUp()
  logger.info("Testing consumer started")

  val monSysId = new Identifier("BoolMonSys", IdentifierType.MONITORED_SOFTWARE_SYSTEM, None)
  val pluginId = new Identifier("BoolPlugin", IdentifierType.PLUGIN, monSysId)
  val converterId = new Identifier("Converter", IdentifierType.CONVERTER, pluginId)

  /** The ID of the sensor8a processed by the DASUs of the Supervisor */
  val sensor8aId = new Identifier("/device_c/sensor8a", IdentifierType.IASIO, converterId)

  /** The ID of the sensor8b processed by the DASUs of the Supervisor */
  val sensor8bId = new Identifier("/device_c/sensor8b", IdentifierType.IASIO, converterId)

  /** The identifier of the supervisor */
  val supervisorId = new Identifier("supervisor", IdentifierType.SUPERVISOR, None)

  /** The kafka consumer gets IASValues from the BSDB */
  val inputConsumer: InputSubscriber = KafkaSubscriber(supervisorId.id, None, None, new Properties())

  /** The test uses real DASU i.e. the factory instantiates a DasuImpl */
  val factory = (dd: DasuDao, i: Identifier, op: OutputPublisher, id: InputSubscriber) => DasuImpl(dd, i, op, id, 1,1)

  // The JSON CDB reader
  val cdbParentPath: Path = FileSystems.getDefault.getPath("src/integrationTest/ias-cdb")
  val cdbReader: CdbReader = new StructuredTextReader(cdbParentPath.toFile)
  cdbReader.init()

  /** The supervisor to test */
  val supervisor = new Supervisor(
    supervisorId,
    KafkaHelper.DEFAULT_BOOTSTRAP_BROKERS,
    inputConsumer,
    cdbReader,
    factory,
    None)

  cdbReader.shutdown()

  // Generator of random numbers
  val randomGenerator = new Random()

  /**
   * Build a [[IASValue]] to submit to the BSDB
   */
  def buildIasValue(identifier: Identifier, value: Double): IASValue[?] = {
    val t0 = System.currentTimeMillis()-100
      IASValue.build(
        value,
        OperationalMode.OPERATIONAL,
        IasValidity.RELIABLE,
        identifier.fullRunningID,
        IASTypes.DOUBLE,
        t0,
        t0+1,
        t0+5,
        t0+10,
        t0+15,
        t0+20,
        null,null,null)
  }

  /**
   *  Get the Alarm out of an IASValue of type ALARM
   * 
   * @returns the Alarm of the passed value or empty if the passed value is of the wrong type
   */
  def extractAlarmVal(iasValue: IASValue[?]): Option[Alarm] = {
    if (iasValue.valueType!=IASTypes.ALARM) Option.empty
    else Some(iasValue.value.asInstanceOf[Alarm])
  }

  /**
   *  Get the double value out of an IASValue of type DOUBLE
   * 
   * @returns the double of the passed value or empty if the passed value is of the wrong type
   */
  def extractDoubleVal(iasValue: IASValue[?]): Option[Double] = {
    if (iasValue.valueType!=IASTypes.DOUBLE) Option.empty
    else Some(iasValue.value.asInstanceOf[Double])
  }

  /**
   *  Get the bool value out of an IASValue of type BOOLEAN
   * 
   * @returns the boolean of the passed value or empty if the passed value is of the wrong type
   */
  def extractBooleanVal(iasValue: IASValue[?]): Option[Boolean] = {
    if (iasValue.valueType!=IASTypes.BOOLEAN) Option.empty
    else Some(iasValue.value.asInstanceOf[Boolean])
  }

  // Get a andom double between [0 and 200] to send as input
  def getRnd(): Double = randomGenerator.nextDouble() * 200.0

  before {
    receivedIasValues.clear()
    receivedIasValuesMap.clear()
  }
  
  after {}

  override def beforeAll(): Unit = {
    logger.info("Running beforeAll")
    /** The listener of IASValues published in the BSDB */
    val iasioListener = new IasioListener {
      /**
        * A value has been read from the BSDB
        * i.e. it has been received by iasiosConsumer
        */
      override def iasiosReceived(events: Collection[IASValue[?]]): Unit = {
        val iasValuesReceived = events.asScala

        logger.info("{} IASValues received", iasValuesReceived.size)

        iasValuesReceived.foreach(iasio => {
          logger.info("IASValue received {}: [{}]", iasio.id, iasio.toString)
          receivedIasValues.append(iasio)
          receivedIasValuesMap += (iasio.id -> iasio)
          logger.info("{} events in the queue", receivedIasValues.size.toString)
        })
      }
    }
    iasiosConsumer.startGettingEvents(StreamPosition.END, iasioListener)

    assert(supervisor.start().isSuccess)
    
    supervisor.enableAutoRefreshOfOutput(false)
    logger.info("beforeAll done.")
  }

  override def afterAll(): Unit = {
    logger.info("AfterAll...")
    iasiosProducer.tearDown()
    iasiosConsumer.tearDown()
    supervisor.close()
    logger.info("AfterAll done")
  }

  behavior of "The Supervisor with boolean TFs"

  it must "activate 7 DASUs with one ASCE each" in {
    assert(supervisor.dasus.values.size == 7)

    assert(supervisor.dasus.values.forall(d => d.getAsceIds().size == 1))
  }

  // The test stresses the Supervisor by sending many inputs for long time 
  // then checks if the Supervisor is still responsive
  it must "still be responsive after stress" in {
    logger.info("Starting responsivness test")
    val in8a = buildIasValue(sensor8aId, 1)
    val in8b = buildIasValue(sensor8bId, 2)
     logger.info(s"sending inputs [${in8a.id}, 1] and [${in8b.id}, 2]")
     iasiosProducer.push(in8a)
     iasiosProducer.push(in8b)

    // Wait all the DASUs to push their outputs in the BSDB
    Thread.sleep(7000)
    assert(receivedIasValuesMap.size==idsOfAllIasValues.size)

    // Sends random inputs
    val iterNum = 5000
    logger.info(s"Runs the stress test by sending {iterNum} times the two inputs ${idsOfInputs.mkString(", ")}")
    (0 until iterNum).foreach { t =>
      val in8a = buildIasValue(sensor8aId, getRnd())
      val in8b = buildIasValue(sensor8bId, getRnd())
      iasiosProducer.push(in8a)
      iasiosProducer.push(in8b)
      val sleepTime = getRnd().toInt
      Thread.sleep(sleepTime)
    }
    logger.info("All inputs sent. Checking if the Supervisor is still responsive")

    Thread.sleep(1000)
    // Disable all the alarms
    iasiosProducer.push(buildIasValue(sensor8aId, 1))
    iasiosProducer.push(buildIasValue(sensor8bId, 1))
    Thread.sleep(7000)
    // Check that all the alarms are clear
    idsOfAlarms.foreach { id =>
      val iasValOpt = receivedIasValuesMap.get(id)
      assert(iasValOpt.isDefined)
      assert(extractAlarmVal(iasValOpt.get).get.alarmState==AlarmState.CLEAR_UNACK)
    }
    // Check that all the booleans are false
    idsOfBools.foreach { id =>
      val iasValOpt = receivedIasValuesMap.get(id)
      assert(iasValOpt.isDefined)
      assert(!extractBooleanVal(iasValOpt.get).get)
    }

    // Enaable all the alarms
    iasiosProducer.push(buildIasValue(sensor8aId, 110))
    iasiosProducer.push(buildIasValue(sensor8bId, 111))
    Thread.sleep(7000)
    // Check that all the alarms are clear
    idsOfAlarms.foreach { id =>
      val iasValOpt = receivedIasValuesMap.get(id)
      assert(iasValOpt.isDefined)
      assert(extractAlarmVal(iasValOpt.get).get.alarmState==AlarmState.SET_UNACK)
    }
    // Check that all the booleans are true
    idsOfBools.foreach { id =>
      val iasValOpt = receivedIasValuesMap.get(id)
      assert(iasValOpt.isDefined)
      assert(extractBooleanVal(iasValOpt.get).get)
    }
  }
  
}
