FROM centos:7

# Install Java
RUN yum update -y && \
  yum install java-1.8.0-openjdk \
  java-1.8.0-openjdk-devel \
  -y

# Install wget and unzip
RUN yum install wget unzip -y

# Install ant
# RUN wget http://archive.apache.org/dist/ant/source/apache-ant-1.9.3-src.zip
# RUN unzip apache-ant-1.9.3-src.zip
RUN wget https://www-eu.apache.org/dist//ant/binaries/apache-ant-1.9.13-bin.zip
RUN unzip apache-ant-1.9.13-bin.zip
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
WORKDIR apache-ant-1.9.13
RUN pwd
RUN chmod +x INSTALL
RUN ./INSTALL
RUN ant -version
RUN yum install ant-contrib-1.0-0.23.b3.el7.noarch


# Install Kafka
RUN wget http://www-us.apache.org/dist/kafka/2.0.0/kafka_2.12-2.0.0.tgz && \
  tar -zxvf kafka_2.12-2.0.0.tgz && \
  mv kafka_2.12-2.0.0 /opt/

# Install Scala
RUN wget https://www.scala-lang.org/files/archive/scala-2.12.6.rpm && \
  rpm -i scala-2.12.6.rpm

# Install Python 3
RUN yum install https://centos7.iuscommunity.org/ius-release.rpm -y && \
  yum install python36u -y && \
  update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1

# Build source code
RUN mkdir -p /usr/src/IntegratedAlarmSystemRoot
WORKDIR /usr/src/ias
COPY . /usr/src/ias

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV JRE_HOME $JAVA_HOME/jre
ENV KAFKA_HOME /opt/kafka_2.12-2.0.0
ENV SCALA_HOME /usr/share/scala
ENV IAS_ROOT /usr/src/IntegratedAlarmSystemRoot

RUN bash -c "source Tools/config/ias-bash-profile.sh"
ENV PATH $PATH:/usr/src/ias/Tools/bin
EXPOSE 2181 9092
