/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0/userguide/multi_project_builds.html
 */

rootProject.name = "ias"
logger.lifecycle("Preparing global settings for {}", rootProject.name)

// The list subprojects: contains all the projects but test-reports
// test-reports is not included because test-reports adds the deps using this list

// and must not contain itself
val subprojectsList = listOf(
    "Tools",
    "Cdb",
    "BasicTypes",
    "CdbChecker",
    "KafkaUtils",
    "Heartbeat",
    "CommandsAndReplies",
    "Plugin",
    "PythonPluginFeeder",
    "Converter",
    "CompElement",
    "DistributedUnit",
    "Supervisor",
    "WebServerSender",
    "TransferFunctions",
    "SinkClient",
    "Extras",
    "Monitor",
    "AlarmGui",
    "test-reports"
)

// INclude all the projects in subprojectsList plust test-reports
include(*subprojectsList.toTypedArray(), "test-reports")

// Expose as Gradle property so that it can be used in test-reports
gradle.extra["aggregatedModules"] = subprojectsList


val pythonVersionComputed = run {
    val process = ProcessBuilder("python3", "-V")
        .redirectErrorStream(true)
        .start()
    val s = process.inputStream.reader(Charsets.UTF_8).use { it.readText().trim() }
    process.waitFor()
    val full = s.substringAfterLast(' ', "")
    require(full.isNotEmpty()) { "Could not read Python version from: '$s'" }
    val majorMinor = if (full.count { it == '.' } >= 2)
        full.substring(0, full.lastIndexOf('.'))
    else full
    "python$majorMinor"
}

val gitBranchProc = ProcessBuilder("git", "rev-parse", "--abbrev-ref", "HEAD").start()
gitBranchProc.inputStream.reader(Charsets.UTF_8).use {
	val gitBranch = it.readText()
	val extension = gradle as ExtensionAware
	extension.extra["GitBranch"] = gitBranch
}
gitBranchProc.waitFor(10, TimeUnit.SECONDS)

// Sets common dependencies
val extension = gradle as ExtensionAware

// Python version
extension.extra["PythonVersion"] = pythonVersionComputed

// IAS common dependencies
extension.extra["scala-library"] = "org.scala-lang:scala3-library_3:3.7.3"
extension.extra["scalatest"] = "org.scalatest:scalatest_3:3.2.19"
extension.extra["slf4j-api"] = "org.slf4j:slf4j-api:2.0.9"
extension.extra["scala-logging"] = "com.typesafe.scala-logging:scala-logging_3:3.9.5"
extension.extra["logback-classic"] = "ch.qos.logback:logback-classic:1.4.11"
extension.extra["jackson-databind"] = "com.fasterxml.jackson.core:jackson-databind:2.17.0"
extension.extra["jep"] ="black.ninia:jep:4.3.1"
extension.extra["junit-jupiter"] = "org.junit.jupiter:junit-jupiter:6.0.0"
extension.extra["junit-jupiter-api"] = "org.junit.jupiter:junit-jupiter-api:6.0.0"
extension.extra["junit-jupiter-engine"] = "org.junit.jupiter:junit-jupiter-engine:6.0.0"
extension.extra["junit-platform-console-standalone"] = "org.junit.platform:junit-platform-console-standalone:6.0.0"
extension.extra["commons-cli"] = "commons-cli:commons-cli:1.5.0"
extension.extra["kafka-clients"] = "org.apache.kafka:kafka-clients:3.7.0"
extension.extra["kafka-streams"] = "org.apache.kafka:kafka-streams:3.7.0"
extension.extra["kafka-connect-api"] = "org.apache.kafka:connect-api:3.7.0"
extension.extra["hibernate-jpa"] = "org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final"

dependencyResolutionManagement {
	repositories {
		mavenCentral()
	}
}

logger.lifecycle("Global settings for {} ready", rootProject.name)
