from Cdb.src.main.python.IasCdb.Dao.IasDao import IasDao


class CdbReader():
    """
    Python class to read the configuration database.
    It is the python implementation of the CdbReader in java
	
	At this stage only the methods needed in other parts fo the IAS
	are implemented: other methods return an exception.
    
    Reading the configuration from the RDB is not supported as the RDB is deprecated
    """
    def getIas(self):
        """
	    Get the Ias configuration from a CDB.
		"""
        raise NotImplementedError

    def getIasios(self) -> IasDao:
        """
        Get the IASIOs.
	    """
        raise NotImplementedError
	
    def getIasio(self, id: str):
        """
        Get the IASIO with the given ID
        """
        raise NotImplementedError
	
	
    def getSupervisor(self, id: str):
        """
        Read the supervisor configuration from the CDB. 
        """
        raise NotImplementedError
	
    def getTransferFunction(self, tf_id: str):
        """
		Read the transfer function configuration from the CDB.
		"""
        raise NotImplementedError

    def getTransferFunctions(self):
        """
        Get the transfer functions.
        """
        raise NotImplementedError

    def getTemplate(self, template_id: str):
        """
        Read the ttemplate configuration from the CDB.
        """
        raise NotImplementedError

    def getTemplates(self):
        """
        Get the templates.
        """
        raise NotImplementedError
	
    def getAsce(self, id: str):
        """
        Read the ASCE configuration from the CDB.
        """
        raise NotImplementedError
	
    def getDasu(self, id: str):
        """
        Read the DASU configuration from the CDB.
        """
        raise NotImplementedError
	
    def getDasusToDeployInSupervisor(self, id: str):
        """
        Return the DASUs to deploy in the Supervisor with the given identifier
        """
        raise NotImplementedError
	
    def getAscesForDasu(self, id: str):
        """
        Return the ASCEs belonging to the given DASU.
        """
        raise NotImplementedError

    def getIasiosForAsce(self, id: str):
        """
        Return the IASIOs in input to the given ASCE.
        """
        raise NotImplementedError

    def getSupervisorIds(self):
       """
       Get the IDs of the Supervisors.
       """
       raise NotImplementedError

    def getDasuIds(self):
       """
       Get the IDs of the DASUs.
       """
       raise NotImplementedError

    def getAsceIds(self):
        """
        Get the IDs of the ASCEs.
        """
        raise NotImplementedError

    def getTemplateInstancesIasiosForAsce(self, id:str):
        """
        Return the templated IASIOs in input to the given ASCE.

        These inputs are the one generated by a different template than
        that of the ASCE (https://github.com/IntegratedAlarmSystem-Group/ias/issues/124)
        """
        raise NotImplementedError

    def getClientConfig(self, id:str):
        """
        Get the configuration of the client with the passed identifier.

        The configuration is passed as a string whose format depends
        on the client implementation.
        """
        raise NotImplementedError

    def getPlugin(self, id:str):
        """
        Get the configuration of the plugin with the passed identifier.
        """
        raise NotImplementedError

    def getPluginIds(self):
        """
        Get the IDs of all the plugins in the CDB
        """
        raise NotImplementedError

    def getClientIds(self):
        """
        Get the IDs of all the plugins in the CDB
        """
        raise NotImplementedError
