package org.eso.ias.cdb.json.pojos;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.Basic;

import org.eso.ias.cdb.pojos.DasuDao;
import org.eso.ias.cdb.pojos.LogLevelDao;

/**
 * Pojo for JSON that replaces object inclusion with their IDS.
 *
 * @see DasuDao
 * @author acaproni
 *
 */
public class JsonDasuDao {
	
	/**
	 * The rdb pojo
	 */
	private final DasuDao dasu;
	
	/**
	 * The IDs of the ASCEs that run into this DASU
	 */
	private final Set<String> asceIDs;
	
	/**
	 * The ID of the output (IASIO) generated by the DASU
	 */
	@Basic(optional=false)
	private String outputId;
	
	/**
	 * The ID of the template for implementing replication
	 */
	@Basic(optional=true)
	private String templateId;
	
	/**
	 * Constructor
	 * 
	 * @param dasu The rdb pojo to mask
	 */
	public JsonDasuDao(DasuDao dasu) {
		if (dasu==null) {
			throw new NullPointerException("The DASU pojo can't be null");
		}
		this.dasu=dasu;
		this.asceIDs=dasu.getAsces().stream().map(i -> i.getId()).collect(Collectors.toSet());
		this.outputId=dasu.getOutput().getId();
		this.templateId=dasu.getTemplateId();
	}
	
	/**
	 * Empty constructor
	 */
	public JsonDasuDao() {
		this.dasu=new DasuDao();
		this.asceIDs=new HashSet<>();
	}

	/**
	 * Return the log level of the DASU
	 * 
	 * @return The log level of teh DASU
	 * @see DasuDao#getLogLevel()
	 */
	public LogLevelDao getLogLevel() {
		return dasu.getLogLevel();
	}

	/**
	 * Set the log level 
	 * 
	 * @param logLevel The log level to set
	 * @see DasuDao#setLogLevel(LogLevelDao)
	 */
	public void setLogLevel(LogLevelDao logLevel) {
		dasu.setLogLevel(logLevel);
	}

	/**
	 * Get the ID of the DASU
	 * 
	 * @return the ID of the DASU
	 * @see DasuDao#getId()
	 */
	public String getId() {
		return dasu.getId();
	}

	/**
	 * Set the ID of the DASU
	 * 
	 * @param id the ID of the DASU
	 * @see DasuDao#setId(java.lang.String)
	 */
	public void setId(String id) {
		dasu.setId(id);
	}

	/**
	 * Get the IDs of the ASCEs running in this DASU
	 * @return the IDs of the ASCEs
	 * @see org.eso.ias.cdb.pojos.DasuDao#getAsces()
	 */
	public Set<String> getAsceIDs() {
		return asceIDs;
	}
	
	/**
	 * Set the IDs of the ASCEs running in this DASU
	 * 
	 * @param ids the IDs of the ASCEs running in this DASU
	 */
	public void setAsceIDs(Set<String> ids) {
		asceIDs.addAll(ids);
	}
	
	/**
	 * toString() prints a human readable version of the DASU
	 * where linked objects (like ASCES) are represented by their
	 * IDs only.
	 */
	@Override
	public String toString() {
		StringBuilder ret = new StringBuilder("jsonDasuAO=[ID=");
		ret.append(getId());
		ret.append("], output ID=[");
		ret.append(getOutputId());
		ret.append("], logLevel=");
		ret.append(getLogLevel());
		ret.append(", ASCEs={");
		for (String asce: getAsceIDs()) {
			ret.append(" ");
			ret.append(asce);
		}
		ret.append("}");
		if (templateId!=null) {
			ret.append(", template=");
			ret.append(templateId);
		}
		ret.append("]");
		return ret.toString();
	}
	
	/**
	 * @return the {@link DasuDao} encapsulated in this object.
	 */
	public DasuDao toDasuDao() {
		dasu.setTemplateId(templateId);
		return this.dasu;
	
	}

	public String getOutputId() {
		return outputId;
	}

	public void setOutputId(String outputId) {
		this.outputId = outputId;
	}

	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((asceIDs == null) ? 0 : asceIDs.hashCode());
		result = prime * result + ((dasu == null) ? 0 : dasu.hashCode());
		result = prime * result + ((outputId == null) ? 0 : outputId.hashCode());
		result = prime * result + ((templateId == null) ? 0 : templateId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JsonDasuDao other = (JsonDasuDao) obj;
		if (asceIDs == null) {
			if (other.asceIDs != null)
				return false;
		} else if (!asceIDs.equals(other.asceIDs))
			return false;
		if (dasu == null) {
			if (other.dasu != null)
				return false;
		} else if (!dasu.equals(other.dasu))
			return false;
		if (outputId == null) {
			if (other.outputId != null)
				return false;
		} else if (!outputId.equals(other.outputId))
			return false;
		if (templateId == null) {
			if (other.templateId != null)
				return false;
		} else if (!templateId.equals(other.templateId))
			return false;
		return true;
	}
}
