#!/usr/bin/awk -f
# This program helps adding/removing items to git
# procesing a file generated by git status>filename.txt
# executed in apidocs
#
#
# USAGE:
# cd ias
# ant doc
# cd $IAS_ROOT/apidocs
# git status >git.status.text
# awk -f apiGitHelper.awk <git.status.text
#
# Always check with git status if something was missing

BEGIN { print "Preparing for git" 
	m = "" 
	d = "" 
	a = "" }
/#[\t ]+modified:[\t ]*.+.(html|js)/ { print  "Modified ==> ["$3"]" 
                                  m = m" \42"$3"\42"  }
/#[\t ]+deleted:[\t ]*.+.(html|js)/ { print  "Deleted ==> ["$3"]" 
				 d = d"  \42"$3"\42" }
/#[\t ]+[^(deleted:|modifiedi:)].+.(html|js)/ { print "New file to add ==> ["$2"]" 
                                           a = a"  \42"$2"\42" }
END { print ""
      print "Run:" 
      print ""
      print "====================================================== ADD"
      print "git add "m 
      print ""
      print "====================================================== RM"
      print "git rm "d
      print ""
      print "====================================================== ADD NEW"
      print "git add "a 
      print "" }
