'''
Created on Jun 7, 2018

@author: acaproni
'''
import json
from datetime import datetime, timedelta
from datetime import timezone
from typing import Self

from IasBasicTypes.Alarm import Alarm
from IasBasicTypes.AlarmState import AlarmState
from IasBasicTypes.Priority import Priority
from IasBasicTypes.IasType import IASType
from IasBasicTypes.Identifier import Identifier
from IasBasicTypes.IdentifierType import IdentifierType
from IasBasicTypes.Iso8601TStamp import Iso8601TStamp
from IasBasicTypes.OperationalMode import OperationalMode
from IasBasicTypes.Validity import Validity


class IasValue(object):
    '''
    The equivalent of IASValue.java in python
    
    Each parameter is present as string or as native type
    for example a timestamp is present as ISO8601 string and datatime,
    the mode is present as string or as OperationalMode
    '''
    
    # The value
    value = None

    # The point in time when the value has been read from the
	# monitored system (set by the plugin only)
    # as ISO 8601 string
    readFromMonSysTStampStr = None

    # The point in time when the value has been read from the
	# monitored system (set by the plugin only)
    # as datetime
    readFromMonSysTStamp = None
    
    # The point in time when the plugin sent the 
    # value to the converter
    # as ISO 8601 string
    sentToConverterTStampStr = None
    
    # The point in time when the plugin sent the 
    # value to the converter
    # as datetime
    sentToConverterTStamp = None
    
    # The point in time when the converter received the  
    # value from the plugin
    # as ISO 8601 string
    receivedFromPluginTStampStr = None
    
    # The point in time when the converter received the  
    # value from the plugin
    # as datetime
    receivedFromPluginTStamp = None
    
    # The point in time when the converter generated
    # the value from the data structure received by the plugin
    # as ISO 8601 string
    convertedProductionTStampStr = None
    
    # The point in time when the converter generated
    # the value from the data structure received by the plugin
    # as datetime
    convertedProductionTStamp = None
    
    # The point in time when the value has been sent to the BSDB
    # as ISO 8601 string
    sentToBsdbTStampStr = None
    
    # The point in time when the value has been sent to the BSDB
    # as datetime
    sentToBsdbTStamp = None
    
    # The point in time when the value has been read from the BSDB
    # as ISO 8601 string
    readFromBsdbTStampStr = None
    
    # The point in time when the value has been read from the BSDB
    # as datetime
    readFromBsdbTStamp = None
    
    # The point in time when the value has been
    # generated by the DASU or the plugin
    # as ISO 8601 string
    productionTStampStr = None
    
    # The point in time when the value has been
    # generated by the DASU or the plugin
    # as datetime
    productionTStamp= None
    
    # The string representation of the mode of the input
    modeStr = None
    
    # The OperationalMode of the input
    mode = None
    
    # The validity
    iasValidityStr = None
    
    # The validity
    iasValidity = None
    
    # The identifier of the input
    id = None
    
    # The full identifier of the input concatenated with
    # that of its parents.
    fullRunningId = None
    
    # The string representation of the IAS type of this input.
    valueTypeStr = None
    
    # The IAS type of this input.
    valueType = None
    
    # The full running identifiers of the dependent
    # monitor point 
    dependentsFullRuningIds = None
    
    # The additional properties
    props = None
    
    def __init__(self, 
                 value,
                 valueType,
                 fullRunningId,
                 mode,
                 iasValidity):
        '''
        Constructor 
        
        @param value the value of the value (string)
        @param valueType the type of the IASIO (IASType or string)
        @param fullRunningId the full running id (String)
        @parm mode the operational mode (string or OperationalMode)
        @param iasValidity the validity (string or Validity)
        '''
        if not value:
            raise ValueError("Invalid value")
        self.value = value
        
        if valueType is None:
            raise ValueError("Invalid type")
        if isinstance(valueType, IASType):
            self.valueType = valueType
            self.valueTypeStr = valueType.name
        else:
            self.valueTypeStr = valueType
            self.valueType = IASType.fromString(valueType)
        
        if not fullRunningId:
            raise ValueError("Invalid full running id")
        self.fullRunningId=fullRunningId
        self.id = self.getIdFromFullRunningId(self.fullRunningId)
        
        if mode is None:
            raise ValueError("Invalid mode")
        if isinstance(mode, OperationalMode):
            self.mode = mode
            self.modeStr = mode.name()
        else:
            self.modeStr = mode
            self.mode = OperationalMode.fromString(mode)
            
        if iasValidity is None:
            raise ValueError("Invalid validity")
        if isinstance(iasValidity, Validity):
            self.iasValidity = iasValidity
            self.iasValidityStr = iasValidity.name()
        else:
            self.iasValidityStr = iasValidity
            self.iasValidity = Validity.fromString(iasValidity)
    
    @classmethod
    def fromJSon(cls, jsonStr) -> Self:
        '''
        Factory method to build a IasValue for a JSON string
        
        @param jsonStr the json string representing the IASValue
        '''
        fromJsonDict = json.loads(jsonStr)
        
        value = fromJsonDict["value"]
        valueTypeStr = fromJsonDict["valueType"]
        fullRunningId = fromJsonDict["fullRunningId"]
        modeStr = fromJsonDict["mode"]
        iasValidityStr = fromJsonDict["iasValidity"]
        
        # If the type is alarm, check if it is valid
        valueType=IASType.fromString(valueTypeStr)
        if valueType is IASType.ALARM:
            alarm = Alarm.fromString(value)
        
        iasValue = IasValue(value,valueType,fullRunningId,modeStr,iasValidityStr)
        
        iasValue.dependentsFullRuningIds = IasValue.getValue(fromJsonDict,"depsFullRunningIds")
        iasValue.props = IasValue.getValue(fromJsonDict,"props")

        iasValue.readFromMonSysTStampStr = IasValue.getValue(fromJsonDict,"readFromMonSysTStamp")
        if iasValue.readFromMonSysTStampStr is not None:
            iasValue.readFromMonSysTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.readFromMonSysTStampStr)
                
        iasValue.sentToConverterTStampStr = IasValue.getValue(fromJsonDict,"sentToConverterTStamp")
        if iasValue.sentToConverterTStampStr is not None:
            iasValue.sentToConverterTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.sentToConverterTStampStr)
            
        iasValue.receivedFromPluginTStampStr = IasValue.getValue(fromJsonDict,"receivedFromPluginTStamp")
        if iasValue.receivedFromPluginTStampStr is not None:
            iasValue.receivedFromPluginTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.receivedFromPluginTStampStr)
            
        iasValue.convertedProductionTStampStr = IasValue.getValue(fromJsonDict,"convertedProductionTStamp")
        if iasValue.convertedProductionTStampStr is not None:
            iasValue.convertedProductionTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.convertedProductionTStampStr)
        
        iasValue.sentToBsdbTStampStr = IasValue.getValue(fromJsonDict,"sentToBsdbTStamp")
        if iasValue.sentToBsdbTStampStr is not None:
            iasValue.sentToBsdbTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.sentToBsdbTStampStr)
        
        iasValue.readFromBsdbTStampStr = IasValue.getValue(fromJsonDict,"readFromBsdbTStamp")
        if iasValue.readFromBsdbTStampStr is not None:
            iasValue.readFromBsdbTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.readFromBsdbTStampStr)
        
        iasValue.productionTStampStr = IasValue.getValue(fromJsonDict,"productionTStamp")
        if iasValue.productionTStampStr is not None:
            iasValue.productionTStamp=Iso8601TStamp.Iso8601ToDatetime(iasValue.productionTStampStr)
            
        return iasValue
        
    def getIdFromFullRunningId(self, frid):
        """
        Extract the id from the fullRunningId
        """
        if frid is None or frid=="":
            raise ValueError("The FullRunning ID cannot be empty")
        
        parts = frid.split("@")
        iasioIdList = [t for t in parts if t.count("IASIO")]
        if len(iasioIdList)!=1:
            raise ValueError("Invalid format of fullRunningId"+frid)
        iasioId=iasioIdList[0]
        if iasioId[0]!='(' or iasioId[len(iasioId)-1]!=')' or iasioId.count(':')!=1:
            raise ValueError("Invalid format of fullRunningId"+frid)
        return iasioId[1:-1].split(":")[0]
    
    @staticmethod
    def getValue(jsonDict,key):
        """
        Get a value from the dictionary, if it exists
        
        @param jsonDict: the dictionary
        @param key: the key
        @return the value of the key if exists, None otherwise
        """
        try:
            ret = jsonDict[key]
        except:
            ret = None
        return ret
    
    def toJSonString(self) -> str:
        """
        @return the JSON representation of the IasValue
        """
        temp = {
             "value":self.value,
             "valueType":self.valueTypeStr,
             "fullRunningId":self.fullRunningId,
             "mode":self.modeStr,
             "iasValidity":self.iasValidityStr
             }
        
        if self.dependentsFullRuningIds is not None:
            temp["depsFullRunningIds"]=self.dependentsFullRuningIds
        if self.props is not None:
            temp["props"]=self.props
        if self.readFromMonSysTStampStr is not None:
            temp["readFromMonSysTStamp"]=self.readFromMonSysTStampStr
        if self.sentToConverterTStampStr is not None:
            temp["sentToConverterTStamp"]=self.sentToConverterTStampStr
        if self.receivedFromPluginTStampStr is not None:
            temp["receivedFromPluginTStamp"]=self.receivedFromPluginTStampStr
        if self.convertedProductionTStampStr is not None:
            temp["convertedProductionTStamp"]=self.convertedProductionTStampStr
        if self.sentToBsdbTStampStr is not None:
            temp["sentToBsdbTStamp"]=self.sentToBsdbTStampStr
        if self.readFromBsdbTStampStr is not None:
            temp["readFromBsdbTStamp"]=self.readFromBsdbTStampStr
        if self.productionTStampStr is not None:
            temp["productionTStamp"]=self.productionTStampStr
             
        return json.dumps(temp)
    
    def toString(self,verbose=False) -> str:
        """
        @param verbose if True prints all the fields
        @return the JSON representation of the IasValue
        """
        temp = {
             "value":self.value,
             "valueType":self.valueTypeStr,
             "fullRunningId":self.fullRunningId,
             "mode":self.modeStr,
             "iasValidity":self.iasValidityStr
             }
        
        if not verbose:
            return "ID=%s, value=%s, type=%s, mode=%s, validity=%s" % \
            (self.id,self.value,self.valueTypeStr,self.modeStr,self.iasValidityStr)
        
        t = "ID="+self.id
        t = t + "\n\tvalue="+self.value
        t = t + "\n\ttype="+self.valueTypeStr
        t = t + "\n\tmode="+self.modeStr
        t = t + "\n\tvalidity="+self.iasValidityStr
        
        
        if self.dependentsFullRuningIds is not None:
            t= "%s\n\tfullRunningID=%s" % (t,self.dependentsFullRuningIds)
            
        if self.props is not None and len(self.props)>0:
            t = t+"\n\tProperties:"
            for k in self.props.keys():
                t = "%s\n\t   %s=%s" % (t,k,self.props[k])

        if self.readFromMonSysTStampStr is not None:
            t = "%s\n\treadFromMonSysTStamp=%s" % (t,self.readFromMonSysTStampStr)
            
        if self.sentToConverterTStampStr is not None:
            t = "%s\n\tsentToConverterTStamp=%s" % (t,self.sentToConverterTStampStr)
            
        if self.receivedFromPluginTStampStr is not None:
            t = "%s\n\treceivedFromPluginTStamp=%s" % (t,self.receivedFromPluginTStampStr)
            
        if self.convertedProductionTStampStr is not None:
            t = "%s\n\tconvertedProductionTStamp=%s" % (t,self.convertedProductionTStampStr)
            
        if self.sentToBsdbTStampStr is not None:
            t = "%s\n\tsentToBsdbTStamp=%s" % (t,self.sentToBsdbTStampStr)
            
        if self.readFromBsdbTStampStr is not None:
            t = "%s\n\treadFromBsdbTStamp=%s" % (t,self.readFromBsdbTStampStr)
            
        if self.productionTStampStr is not None:
            t = "%s\n\tproductionTStamp=%s" % (t,self.productionTStampStr)
             
        return t
    
    @staticmethod
    def _build_timestamps(fr_id: Identifier) -> dict[str, str]:
        """
        Build a dictionary with reasonable timestamps for the IASIO to push.
        It is an helper function for testing.

        The timestamps are built based on the actual time, with a reasonable delay between them.
        The timestamps are returned as a dictionary with the same keys as the IasValue json string.

        It produces a different sets of timestamps depending if the IASIO is produced by a plugin
        or by a DASU. The producer of the IASIO can be inferred by the full running ID: 
        if it contains a DASU, it is produced by a DASU, otherwise it is produced by a plugin.

        :param fr_id: The full running ID of the IASIO 
        :type fr_id: Identifier
        :return: A dictionary with the timestamps
        :rtype: dict
        """

        # The actual time, now, is used for the sent to BSDB timestamp
        # Other timestamps are relative to this timestamp
        now = datetime.now(timezone.utc)

        # The ofsset fpor the timestamps relative to the production timestamp
        time_offset = timedelta(milliseconds=10)

        produced_by_plugin = fr_id.get_id_of_type(IdentifierType.PLUGIN) is not None

        timestamps = {}

        if produced_by_plugin:
            timestamps["readFromMonSysTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-5*time_offset)
            timestamps["productionTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-4*time_offset) # Produced by th eplugin
            timestamps["sentToConverterTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-3*time_offset) # Sent by the plugin to the converter
            timestamps["receivedFromPluginTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-2*time_offset) # Received by converter
            timestamps["convertedProductionTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-time_offset) # Converted by the converter
            timestamps["sentToBsdbTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now) # Sent by the converter to the BSDB
        else: # DASU
            timestamps["productionTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now-time_offset) #Produced by DASU
            timestamps["sentToBsdbTStamp"] = Iso8601TStamp.datetimeToIsoTimestamp(now) # Sent to BSDB

        return timestamps

    @classmethod
    def build(cls,
        value: str,
        value_type: IASType,
        fr_id: Identifier,
        validity: Validity,
        mode: OperationalMode,
        props: dict[str, str]|None = None) -> Self:
        """
        Factory method to build a IasValue useful for tetsing.

        This function builds a IasValue building the json string from the passed
        parameters and invoking IasValue.fromJSon(): it makes no check on the coinsistency of the passed parameters.
        For example it does not check if the value is consistent with the type.

        It assigns a reasonable set of timestamps by delegating to `_build_timestamps`.

        Properties are not supported.

        :param value: The value of the IASIO
        :type value: str
        :param value_type: The type of the IASIO
        :type value_type: IASType
        :param fr_id: The full running ID of the IASIO
        :type fr_id: Identifier
        :param validity: The validity of the IASIO
        :type validity: Validity
        :param mode: The operational mode of the IASIO
        :type mode: OperationalMode
        :param props: The properties of the IASIO
        :type props: dict[str, str]|None
        
        :return: Description
        :rtype: IasValue
        """
        value_dict = {}
        value_dict = value_dict | cls._build_timestamps(fr_id)
        value_dict["value"] = value
        value_dict["valueType"] = value_type.name
        value_dict["mode"] = mode.name
        value_dict["iasValidity"] = validity.name
        value_dict["fullRunningId"] = str(fr_id)
        if props:
            value_dict["props"] = props
        
        return cls.fromJSon(json.dumps(value_dict))
    
    @classmethod
    def build_alarm(cls,
        alarm_state: AlarmState,
        alarm_priority: Priority,
        fr_id: Identifier,
        validity: Validity,
        mode: OperationalMode,
        props: dict[str, str]|None = None) -> Self:
        """
        Factory method to build a IasValue of type ALARM useful for testing.

        This function builds a IasValue building the json string from the passed
        parameters and invoking IasValue.fromJSon(): it makes no check on the coinsistency of the passed parameters.
        For example it does not check if the value is consistent with the type.

        It assigns a reasonable set of timestamps by delegating to `_build_timestamps`.

        Properties are not supported.

        :param value: The value of the IASIO
        :type value: str
        :param value_type: The type of the IASIO
        :type value_type: IASType
        :param fr_id: The full running ID of the IASIO
        :type fr_id: Identifier
        :param validity: The validity of the IASIO
        :type validity: Validity
        :param mode: The operational mode of the IASIO
        :type mode: OperationalMode
        :param props: The properties of the IASIO
        :type props: dict[str, str]|None
        
        :return: Description
        :rtype: IasValue
        """
        value_dict = {}
        value_dict = value_dict | cls._build_timestamps(fr_id)
        value_dict["value"] = f"{alarm_state.name}:{alarm_priority.name}"
        value_dict["valueType"] = IASType.ALARM.name
        value_dict["mode"] = mode.name
        value_dict["iasValidity"] = validity.name
        value_dict["fullRunningId"] = str(fr_id)
        if props:
            value_dict["props"] = props
        
        return cls.fromJSon(json.dumps(value_dict))
    