"""
The type of an Identifier (python equivalent of Identifier.java)
"""

from enum import Enum, unique
from typing import Tuple

@unique
class IdentifierType(Enum):
    """
    The types of an identifier
    
    There is a relationship between types, meaning that
    a type can have zero, one or more types of parents of a specified type.

    Note: IAS tools sends a Heartbeat with their identifier that is another type
          of identifier defined in the Heartbeat module.
          The reason of the separation of the 2 types of identifiers is documented in
          issue #145 and #149

    See: Identifier
    """
    # The type for the monitored software system that
    # produced a monitor point value or alarm
    # For example: [ID=ACS, type=MONITORED_SOFTWARE_SYSTEM]
    MONITORED_SOFTWARE_SYSTEM = 1 
    
    # The type of a plugin that retrieved
    # a monitor point value or alarm from a monitored system
    # For example: [ID=ACS_Plugin, type=PLUGIN]
    PLUGIN = 2
    
    # The type of the identifier for the converter
    # that translates a value or alarm produced by a remote
    # monitored system into a valid IAS data structure.
    CONVERTER = 3
    
    # The type of a supervisor identifier
    SUPERVISOR = 4
    
    # The type of a distributed unit identifier that runs in a supervisor
    DASU = 5
    
    # The type of a computing element identifier that runs in a DASU
    ASCE = 6
    
    # A CORE tool that can generate alarms.
    CORETOOL = 7
    
    # A IAS client that does not generate alarms
    # GUIs are an example of CLIENT; a tool to send commands is another example.
    CLIENT = 8
    # The type of IASIO identifier.
    # The IASIO can be generated by:
    # - a converter (ultimately by a plugin)
    # - an ASCE
    # - a CORE tool
    IASIO = 9
    
    def __init__(self, val) -> None:
        """
        Initialize IdentifierType enum member.
        """

        # The parents of the Identifier to be filled after enum creation
        self.parents = []

    @staticmethod
    def from_string(identifier_type: str):
        if not identifier_type:
            raise ValueError("Invalid string representation of the exit status of a comamnd")
        try:
            return IdentifierType[identifier_type]
        except KeyError:
            raise ValueError("Not supported/find IAS identifier type: " + identifier_type)

# --- Assign parents AFTER enum creation ---
IdentifierType.MONITORED_SOFTWARE_SYSTEM.parents = []
IdentifierType.PLUGIN.parents = [IdentifierType.MONITORED_SOFTWARE_SYSTEM]
IdentifierType.CONVERTER.parents = [IdentifierType.PLUGIN]
IdentifierType.SUPERVISOR.parents = []
IdentifierType.DASU.parents = [IdentifierType.SUPERVISOR]
IdentifierType.ASCE.parents = [IdentifierType.DASU]
IdentifierType.CORETOOL.parents = []
IdentifierType.CLIENT.parents = []
IdentifierType.IASIO.parents = [IdentifierType.CONVERTER, IdentifierType.ASCE, IdentifierType.CORETOOL]
