package org.eso.ias.types;

/**
 * The types of an identifier of an IASIO.
 * <P>
 * There is a relationship between types, meaning that
 * a type can have zero, one or more types of parents of a specified type.
 *
 * Note: IAS tools sends an Heartbeat with their identifier that is another type
 *       of identifier defined in the Heartbeat module.
 *       The reason of the separation of the 2 types of identifiers is documented in
 *       [[https://github.com/IntegratedAlarmSystem-Group/ias/issues/145 #145]] and
 *       [[https://github.com/IntegratedAlarmSystem-Group/ias/issues/149 #149]]
 *
 * @author acaproni
 * @see Identifier
 */
public enum IdentifierType {
	
	/**
	 * The type for the monitored software system that
	 * produced a monitor point value or alarm
	 * <P>
	 * For example: [ID=ACS, type={@link #MONITORED_SOFTWARE_SYSTEM}]
	 * 
	 */
	MONITORED_SOFTWARE_SYSTEM(),
	
	/**
	 * The type of a plugin that retrieved
	 * a monitor point value or alarm from a monitored system
	 * <P>
	 * For example: [ID=ACS_Plugin, type={@link #PLUGIN}
	 */
	PLUGIN(MONITORED_SOFTWARE_SYSTEM),
	
	/**
	 * The type of the identifier for the converter
	 * that translates a value or alarm produced by a remote
	 * monitored system into a valid IAS data structure.
	 */
	CONVERTER(PLUGIN),
	
	/**
	 * The type of a supervisor identifier
	 */
	SUPERVISOR(),
	
	/**
	 * The type of a distributed unit identifier that runs in a superivisor
	 */
	DASU(SUPERVISOR),
	
	/**
	 * The type of a computing element identifier that runs in a DASU
	 */
	ASCE(DASU),

	/**
	 * A CORE tool that can generate alarms.
	 */
	CORETOOL(),

	/**
	 * A IAS client that does not generate alarms
	 *
	 * GUIs are an example of CLIENT; a tool to send commands is another example.
	 */
	CLIENT(),
	
	/**
	 * The type of IASIO identifier.
	 *
	 * The IASIO can be generated by
	 * - a converter (ultimately by a plugin)
	 * - an ASCE
	 * - a CORE tool
	 */
	IASIO(CONVERTER, ASCE, CORETOOL);

	/**
	 * Possible parents of a identifier
	 */
	public final IdentifierType[] parents;
	
	/**
	 * Constructor 
	 * @param theParents The parents of the type
	 */
	private IdentifierType(IdentifierType... theParents) {
		parents = theParents;
	}
}
