package org.eso.ias.transfer.test

import java.util.Properties
import org.scalatest.flatspec.AnyFlatSpec

import org.eso.ias.logging.IASLogger
import org.eso.ias.types.{IASTypes, Alarm, Identifier, IdentifierType, InOut, AlarmState, Priority}
import org.eso.ias.transfer.AndAlarm
import org.eso.ias.types.{Identifier, IdentifierType, InOut, IASTypes}
import org.eso.ias.asce.exceptions.{UnexpectedNumberOfInputsException}
import org.eso.ias.asce.transfer.{IasIO, IasioInfo}

/** Test the [[org.eso.ias.tranfer.AndAlarm]] transfer function */
class AndAlarmTest extends AnyFlatSpec {
  /** The logger */
  private val logger = IASLogger.getLogger(this.getClass)

  /**  The ID of the SUPERVISOR where the components runs */
  val supervId = new Identifier("SupervId",IdentifierType.SUPERVISOR,None)

  /**  The ID of the DASU where the components runs */
  val dasuId = new Identifier("DasuId",IdentifierType.DASU,supervId)

  /** The ID of the component running into the DASU */
  val compID = new Identifier("ASCE-ID-ForTest",IdentifierType.ASCE,Option(dasuId))

  /** The ID of the output generated by the component */
  val outId = new Identifier("OutputId",IdentifierType.IASIO, Some(compID))

  /** the IASIO in output */
  val out: IasIO[Alarm] = new IasIO(InOut.asOutput(outId,IASTypes.ALARM))

  /** Ouput info for the initialize */
  val outputInfo = new IasioInfo(outId.id,IASTypes.ALARM)

  /** The Map of IASValues for updating the inputs to the ASCE */
  val inputsMPs: Set[InOut[?]]  = {
    val v = for (i <- 1 to 5) yield {
    InOut.asInput(
        new Identifier("ALARM INPUT-HIO-ID#"+i, IdentifierType.IASIO,compID),
        IASTypes.ALARM)  
    }
    v.toSet
  }

  /** The time frame for the validity */
  val validityTimeFrame = 2000

  behavior of "The AndAlarm TF"

  it must "get invert logic from props or use the default" in {
    val props = new Properties()
    val tf = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(!tf.invert)

    props.put(AndAlarm.InvertLogicPropName,"False")
    val tf2 = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(!tf2.invert)

    props.put(AndAlarm.InvertLogicPropName,"True")
    val tf3 = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(tf3.invert)
  }

  it must "fail if the number of inputs is less than 2" in {
    val props = new Properties()
    val tf = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assertThrows[UnexpectedNumberOfInputsException] {
      tf.initialize(Set.empty, outputInfo)
    }

    val tf2 = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assertThrows[UnexpectedNumberOfInputsException] {
      tf2.initialize(Set(new IasioInfo("input1", IASTypes.ALARM)), outputInfo)
    }

    val tf3 = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    val inputs = Set(new IasioInfo("input1", IASTypes.ALARM), new IasioInfo("input2", IASTypes.BOOLEAN))
    assertThrows[java.lang.IllegalArgumentException] {
      tf3.initialize(inputs, outputInfo)
    }

    val tf4 = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props)
    val inputsd = Set(new IasioInfo("input1", IASTypes.ALARM), new IasioInfo("input2", IASTypes.ALARM))
    tf4.initialize(inputsd, outputInfo)
  }

  it must "return TRUE if all the alarm inputs are SET (including the inverted logic)" in  {
    val props_normal = new Properties()
    props_normal.put(AndAlarm.InvertLogicPropName, "False")
    val tf_normal = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props_normal)

    val props_inverted = new Properties()
    props_inverted.put(AndAlarm.InvertLogicPropName, "True")
    val tf_inverted = new AndAlarm(compID.id, compID.fullRunningID, validityTimeFrame, props_inverted)

    val iasiosInfo = inputsMPs.map(i => new IasioInfo(i.id.id, IASTypes.ALARM))
    tf_normal.initialize(iasiosInfo, outputInfo)
    tf_inverted.initialize(iasiosInfo, outputInfo)

    val allFalseInputs: Map[String,IasIO[?]] = inputsMPs.map(i => i.id.id -> new IasIO(i.updateValue(Some(Alarm.getInitialAlarmState())))).toMap

    val ret_normal = tf_normal.eval(allFalseInputs,out)
    assert(ret_normal.value.isDefined)
    assert(ret_normal.value.get.isCleared()) // Not set

    val ret_inverted = tf_inverted.eval(allFalseInputs,out)
    assert(ret_inverted.value.isDefined)
    assert(ret_inverted.value.get.isSet()) // Set because of the inverted logic

    val allTrueInputs: Map[String,IasIO[?]] = inputsMPs.map(i => i.id.id -> new IasIO(i.updateValue(Some(Alarm.getInitialAlarmState().set())))).toMap

    val ret_normal2 = tf_normal.eval(allTrueInputs,out)
    assert(ret_normal2.value.isDefined)
    assert(ret_normal2.value.get.isSet()) 
    val ret_inverted2 = tf_inverted.eval(allTrueInputs,out)
    assert(ret_inverted2.value.isDefined)
    assert(ret_inverted2.value.get.isCleared())

    val mixedInputs: Map[String, IasIO[?]] =
      inputsMPs.zipWithIndex.map { case (i, idx) =>
        val flag = idx % 2 == 0   // even index → set, odd → clear
        if (flag) {
          i.id.id -> new IasIO(i.updateValue(Some(Alarm.getInitialAlarmState().set())))
        } else {
          i.id.id -> new IasIO(i.updateValue(Some(Alarm.getInitialAlarmState())))
        }
      }.toMap

    val ret_normal_mixed = tf_normal.eval(mixedInputs,out)
    assert(ret_normal_mixed.value.isDefined)
    assert(ret_normal_mixed.value.get.isCleared())

    val ret_inverted_mixed = tf_inverted.eval(mixedInputs,out)
    assert(ret_inverted_mixed.value.isDefined)
    assert(ret_inverted_mixed.value.get.isSet())
  }
}
