package org.eso.ias.transfer.test

import java.util.Properties
import org.scalatest.flatspec.AnyFlatSpec

import org.eso.ias.logging.IASLogger
import org.eso.ias.transfer.OrBool
import org.eso.ias.types.{Identifier, IdentifierType, InOut, IASTypes}
import org.eso.ias.asce.exceptions.{UnexpectedNumberOfInputsException}
import org.eso.ias.asce.transfer.{IasIO, IasioInfo}

/** Test the [[org.eso.ias.tranfer.OrBool]] transfer function */
class OrBoolTest extends AnyFlatSpec {
  /** The logger */
  private val logger = IASLogger.getLogger(this.getClass)

  /**  The ID of the SUPERVISOR where the components runs */
  val supervId = new Identifier("SupervId",IdentifierType.SUPERVISOR,None)

  /**  The ID of the DASU where the components runs */
  val dasuId = new Identifier("DasuId",IdentifierType.DASU,supervId)

  /** The ID of the component running into the DASU */
  val compID = new Identifier("ASCE-ID-ForTest",IdentifierType.ASCE,Option(dasuId))

  /** The ID of the output generated by the component */
  val outId = new Identifier("OutputId",IdentifierType.IASIO, Some(compID))

  /** the IASIO in output */
  val out: IasIO[Boolean] = new IasIO(InOut.asOutput(outId,IASTypes.BOOLEAN))

  /** Ouput info for the initialize */
  val outputInfo = new IasioInfo(outId.id,IASTypes.BOOLEAN)

  /** The Map of IASValues for updating the inputs to the ASCE */
  val inputsMPs: Set[InOut[?]]  = {
    val v = for (i <- 1 to 5) yield {
    InOut.asInput(
        new Identifier("BOOL INPUT-HIO-ID#"+i, IdentifierType.IASIO,compID),
        IASTypes.BOOLEAN)  
    }
    v.toSet
  }

  /** The time frame for the validity */
  val validityTimeFrame = 2000

  behavior of "The OrBool TF"

  it must "get invert logic from props or use the default" in {
    val props = new Properties()
    val tf = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(!tf.invert)

    props.put(OrBool.InvertLogicPropName,"False")
    val tf2 = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(!tf2.invert)

    props.put(OrBool.InvertLogicPropName,"True")
    val tf3 = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assert(tf3.invert)
  }

  it must "fail if the number of inputs is less than 2" in {
    val props = new Properties()
    val tf = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assertThrows[UnexpectedNumberOfInputsException] {
      tf.initialize(Set.empty, outputInfo)
    }

    val tf2 = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    assertThrows[UnexpectedNumberOfInputsException] {
      tf2.initialize(Set(new IasioInfo("input1", IASTypes.BOOLEAN)), outputInfo)
    }

    val tf3 = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    val inputs = Set(new IasioInfo("input1", IASTypes.BOOLEAN), new IasioInfo("input2", IASTypes.BOOLEAN))
    tf3.initialize(inputs, outputInfo)
  }

  it must "return TRUE if all the boolean inputs are true (including the inverted logic)" in  {
    val props_normal = new Properties()
    props_normal.put(OrBool.InvertLogicPropName, "False")
    val tf_normal = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props_normal)

    val props_inverted = new Properties()
    props_inverted.put(OrBool.InvertLogicPropName, "True")
    val tf_inverted = new OrBool(compID.id, compID.fullRunningID, validityTimeFrame, props_inverted)

    val iasiosInfo = inputsMPs.map(i => new IasioInfo(i.id.id, IASTypes.BOOLEAN))
    tf_normal.initialize(iasiosInfo, outputInfo)
    tf_inverted.initialize(iasiosInfo, outputInfo)

    val allFalseInputs: Map[String,IasIO[?]] = inputsMPs.map(i => i.id.id -> new IasIO(i.updateValue(Some(false)))).toMap

    val ret_normal = tf_normal.eval(allFalseInputs,out)
    assert(ret_normal.value.isDefined)
    assert(!ret_normal.value.get)

    val ret_inverted = tf_inverted.eval(allFalseInputs,out)
    assert(ret_inverted.value.isDefined)
    assert(ret_inverted.value.get)

    val allTrueInputs: Map[String,IasIO[?]] = inputsMPs.map(i => i.id.id -> new IasIO(i.updateValue(Some(true)))).toMap

    val ret_normal2 = tf_normal.eval(allTrueInputs,out)
    assert(ret_normal2.value.isDefined)
    assert(ret_normal2.value.get)

    val ret_inverted2 = tf_inverted.eval(allTrueInputs,out)
    assert(ret_inverted2.value.isDefined)
    assert(!ret_inverted2.value.get)

    val mixedInputs: Map[String, IasIO[?]] =
      inputsMPs.zipWithIndex.map { case (i, idx) =>
        val flag = idx % 2 == 0   // even index → true, odd → false
        i.id.id -> new IasIO(i.updateValue(Some(flag)))
      }.toMap

    val ret_normal_mixed = tf_normal.eval(mixedInputs,out)
    assert(ret_normal_mixed.value.isDefined)
    assert(ret_normal_mixed.value.get)

    val ret_inverted_mixed = tf_inverted.eval(mixedInputs,out)
    assert(ret_inverted_mixed.value.isDefined)
    assert(!ret_inverted_mixed.value.get)
  }
}
