package org.eso.ias.transfer.test

import java.util.Properties
import org.eso.ias.logging.IASLogger
import org.eso.ias.types.{Identifier, IdentifierType, InOut, IASTypes}
import org.eso.ias.asce.transfer.{IasIO, IasioInfo}
import org.eso.ias.transfer.MinMaxBool

import org.scalatest.flatspec.AnyFlatSpec

class TestMinMaxBool extends AnyFlatSpec {

  /** The logger */
  private val logger = IASLogger.getLogger(this.getClass)

  /**  The ID of the SUPERVISOR where the components runs */
  val supervId = new Identifier("SupervId",IdentifierType.SUPERVISOR,None)

  /**  The ID of the DASU where the components runs */
  val dasuId = new Identifier("DasuId",IdentifierType.DASU,supervId)

  /** The ID of the component running into the DASU */
  val compID = new Identifier("ASCE-ID-ForTest",IdentifierType.ASCE,Option(dasuId))

  /** The ID of the output generated by the component */
  val outId = new Identifier("OutputId",IdentifierType.IASIO, Some(compID))

  /** the IASIO in output */
  val out: IasIO[Boolean] = new IasIO(InOut.asOutput(outId,IASTypes.BOOLEAN))

  /** Ouput info for the initialize */
  val outputInfo = new IasioInfo(outId.id,IASTypes.BOOLEAN)

  /** The Map of IASValues for updating the inputs to the ASCE */
  val inputMP:InOut[?] = InOut.asInput(
      new Identifier("LONG-INPUT-ID", IdentifierType.IASIO,compID),
      IASTypes.LONG)  

  val inputInfo = new IasioInfo(inputMP.id.id,IASTypes.LONG)

  /** The time frame for the validity */
  val validityTimeFrame = 2000

  
  behavior of "The scala MinMaxBool TF"
  
  it must "run the scala Min/Max-Bool TF executor" in { 
    val props = new Properties()
    props.put(MinMaxBool.highOnPropName, "50")
    props.put(MinMaxBool.highOffPropName, "25")
    props.put(MinMaxBool.lowOffPropName, "-10")
    props.put(MinMaxBool.lowOnPropName, "-20")

    // The TF to test
    val tf = new MinMaxBool(compID.id, compID.fullRunningID, validityTimeFrame, props)
    tf.initialize(Set(inputInfo), outputInfo)
    
    // Too high must return true
    val first = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(60L)))), out)
    assert(first.value.get)
    
    // Increase more still returns true
    val output = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(150L)))), first)
    assert(output.value.get)
    

    output.props.keys.foreach(k => logger.info("Property of output with backup {}->{}",k,output.props(k)))
    val propValueMap2=output.props.get(MinMaxBool.actualValuePropName)
    assert(propValueMap2.isDefined)
    assert(propValueMap2.get.contains(150L.toDouble.toString()))
    
    // Decreasing without passing HighOn returns true
    val output2 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(40L)))), output)
    assert(output2.value.get)
    
    // Below HighOff returns false
    val output3 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(10L)))), output2)
    assert(!output3.value.get)
    
    val propValueMap3=output3.props.get(MinMaxBool.actualValuePropName)
    assert(propValueMap3.isDefined)
    assert(propValueMap3.get.contains(10L.toDouble.toString()))
    
    // Below LowOff but not passing LowOn returns false
    val output4 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(-15L)))), output3)
    assert(!output4.value.get)
    
    // Passing LowOn return true
    val output5 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(-30L)))), output4)
    assert(output5.value.get)
    
    // Decreasing more remain true
    val output6 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(-40L)))), output5)
    assert(output6.value.get)
    
    // Increasing but not passing LowOff remains true
    val output7 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(-15L)))), output6)
    assert(output7.value.get)
    
    // Passing LowOff returns false
    val output8 = tf.eval( Map(inputMP.id.id -> new IasIO(inputMP.updateValue(Some(0L)))), output7)
    assert(!output8 .value.get)
  }
}
