'''

Base class for java, scal and python API docs generators
Created on Jul 7, 2017

@author: acaproni
'''

import sys
import os

class DocGenerator(object):
    '''
    The base class for API docs generators
    '''


    def __init__(self,srcFolder,dstFolder,outFile=sys.stdout):
        """ 
        Constructor
        @param srcFolder: the folder with java sources to generate their documentation
        @param dstFolder: destination folder for javadocs  
        @param outFile: the file where the output generated by calling javadoc must be sent
        """
        self.checkFolders(srcFolder,dstFolder)
        self.srcFolder=srcFolder
        self.dstFolder=dstFolder
        self.outFile=outFile
        assert self.outFile is not None
        
    def checkFolders(self,src,dst):
        """
        Check if the source and dest folders are valid and if it is not the case,
        throws an exception
        @param src: the folder with java sources to check
        @param dst: destination folder to check
        """
        # Check if src folder exists
        if not os.path.exists(src):
            raise IOError("The source folder", src,"does not exist")
        elif not os.path.isdir(src):
            raise IOError("The source folder", src,"is not a directory")
            
        # Check if the destination folder exists
        if not os.path.exists(dst):
            raise IOError("The destination folder", dst,"does not exist")
        elif not os.path.isdir(dst):
            raise IOError("The destination folder", dst,"is not a directory")