'''
API python documentation builder.

Created on Jul 7, 2017

@author: acaproni
'''

import sys
import os
import shutil
from subprocess import call
from IASApiDocs.DocGenerator import DocGenerator

class PydocBuilder(DocGenerator):
    '''
    Builds python API documentation, delegating to pydoc
    '''


    def __init__(self,srcFolder,dstFolder,includeTestFolder=False,outFile=sys.stdout):
        """ 
        Constructor
        @param srcFolder: the folder with java sources to generate their documentation
        @param dstFolder: destination folder for javadocs  
        @param includeTestFolder: True if the class must generate documentation for the java
                sources in test folders (defaults to False)
        @param outFile: the file where the output generated by calling javadoc must be sent
        """
        self.includeTestFolder=includeTestFolder
        super(PydocBuilder, self).__init__(srcFolder,dstFolder,outFile)
        
    def buildPydocs(self):
        """
        Build the pydocs 
        
        Generation of pydocs is delegated to pydoc executable
        
        @return: the code returned by calling javadoc
        """
        
        folders = self.getSrcPaths(self.srcFolder, False,"python",".py")
        
        print folders
        
        for folder in folders:
            print "Generating pydoc in",folder
            cmd =["pydoc"]
            cmd.append("-w")
            cmd.append(folder+os.path.sep)
            
            ret = call(cmd,stdout=self.outFile,stderr=self.outFile)
            
            print "Moving htmls to",self.dstFolder
            files = os.listdir(".")
            for f in files:
                if (f.endswith(".html")):
                    shutil.move(f, self.dstFolder)
        
        return ret
        