DROP TABLE PROPERTY CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE PROP_SEQ_GENERATOR;
DROP TABLE IAS CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE IAS_SEQ_GENERATOR;
DROP TABLE IAS_PROPERTY CASCADE CONSTRAINTS PURGE;
DROP TABLE IASIO CASCADE CONSTRAINTS PURGE;