top = '.'
out = 'build'

import os

def options(conf):
    pass

def configure(conf):
    pass

def makeInstall(ctx):
    from IasWafBuildTools.Utils import set_env
    ctx.bldnode=ctx.path.make_node('build')
    set_env(ctx.env,ctx.path,ctx.bldnode)
    from IasWafBuildTools.Installer import Installer
    installer = Installer(ctx, ctx.env.DSTNODE, ctx.env.PREFIX)
    installer.install()

def makeBuild(bld):
    from IasWafBuildTools.Utils import set_env
    bld.bldnode=bld.path.make_node('build')
    set_env(bld.env,bld.path,bld.bldnode)

    print("Building",bld.path.abspath())

    print("Tools Root abspath",bld.root.abspath())
    print("Tools bld.path contents %r" % bld.path.children)
    print("Tools bld.path parent   %r" % bld.path.parent.abspath())
    print("Tools bld.root parent   %r" % bld.root.parent)
    print("Tools bld.top_dir   %r" % bld.top_dir)
    print("Tools Build node",bld.bldnode)

    print("\n",bld)

    #
    # get jars from ZIP
    #
    spring_release = "4.3.9"
    zipFileName="spring-framework-{}.RELEASE-dist.zip".format(spring_release)

    jarsInZip = [
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("spring-core-{}.RELEASE.jar".format(spring_release)),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("spring-context-{}.RELEASE.jar".format(spring_release)),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("spring-beans-{}.RELEASE.jar".format(spring_release)),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("spring-aop-{}.RELEASE.jar".format(spring_release)),
        bld.env.BLDEXTTOOLSFOLDER.find_or_declare("spring-expression-{}.RELEASE.jar".format(spring_release))
    ]

    print("jars to get from ZIP",jarsInZip)


    from IasWafBuildTools.JarTasks import getJarsFromZip

    jarsFromZipTask = getJarsFromZip(env=bld.env)
    jarsFromZipTask.color='YELLOW'
    jarsFromZipTask.set_inputs(bld.env.SRCEXTTOOLSFOLDER.find_node(zipFileName))
    jarsFromZipTask.set_outputs(jarsInZip)
    bld.add_to_group(jarsFromZipTask)

    #
    # get Jars from extTools
    #
    from IasWafBuildTools.FileTasks import CopyTask
    copyExtJarTask = CopyTask(bld.env, bld.env.SRCEXTTOOLSFOLDER, file_extension=".jar")
    copyExtJarTask.color= 'CYAN'
    bld.add_to_group(copyExtJarTask)

    #
    # Get jar from tar
    #
    tarFileName="commons-cli-1.4-bin.tar.gz"
    tarFileNode = bld.env.SRCEXTTOOLSFOLDER.find_node(tarFileName)

    from IasWafBuildTools.JarTasks import getJarsFromTar
    getJarsFromTarTask = getJarsFromTar(env=bld.env)
    getJarsFromTarTask.set_inputs(tarFileNode)
    getJarsFromTarTask.set_outputs(bld.env.BLDEXTTOOLSFOLDER.find_or_declare("commons-cli-1.4.jar"))
    getJarsFromTarTask.color='PINK'
    bld.add_to_group(getJarsFromTarTask)

    #
    # Python modules
    #
    from IasWafBuildTools.PythonBuilder import BuildPythonModules
    bldPyMods = BuildPythonModules(bld.env)
    bldPyMods.color='RED'
    bld.add_to_group(bldPyMods)

    #
    # Config files
    #
    copyConfigFiles = CopyTask(bld.env, bld.env.CONFIGSRCFOLDER)
    copyConfigFiles.color= 'CYAN'
    bld.add_to_group(copyConfigFiles)

    #
    # Shell scripts
    #
    bldShScripts = CopyTask(
        bld.env,
        bld.env.SRCMAINFOLDER,
        bld.env.BLDBINFOLDER,
        remove_etension=True,
        make_executable=True,
        file_extension=".sh"
    )
    bldShScripts.color='YELLOW'
    bld.add_to_group(bldShScripts)

    #
    # Python scripts
    #
    bldPyScripts = CopyTask(
        bld.env,
        bld.env.PYSRCFOLDER,
        bld.env.BLDBINFOLDER,
        remove_etension=True,
        make_executable=True,
        file_extension=".py"
    )
    bldPyScripts.color='GREY'
    bld.add_to_group(bldPyScripts)

    if str(bld.top_dir) != str(bld.path.abspath()):
        print("=====>>> Tools requesting install: ",bld.cmd,bld.top_dir,bld.path.abspath())
        makeInstall(bld)

def build(bld):
    bld.load('IasWafBuildTools', tooldir='../WafBuildTools/src/main/python/')
    print('=====>>> Tools is_install',bld.is_install)
    print('=====>>> Tools build command',bld.cmd)

    bld.env.PREFIX = os.environ['IAS_ROOT']

    if bld.cmd == 'build':
        print('=====>>> Tools build...',bld.cmd)
        makeBuild(bld)
    elif bld.cmd == 'install':
        print('=====>>> Tools install...',bld.cmd)
        makeInstall(bld)




    print("Building of", bld.path.abspath(), "done.")
