package org.eso.ias.cdb.pojos;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.ForeignKey;

/**
 * 
 * The pojo for the ASCE
 * 
 * @author acaproni
 *
 */
@Entity
@Table(name = "ASCE")
public class AsceDao {

	@Id
	@Column(name = "asce_id")
	private String id;
	
	/**
	 * The DASU that runs this ASCE 
	 */
	@ManyToOne
    @JoinColumn(name = "dasu_id", foreignKey = @ForeignKey(name = "dasu_id")
    )
    private DasuDao dasu;
	
	/**
	 * The jvm class of the transfer function
	 */
	@Basic(optional=false)
	private String tfClass;
	
	/**
	 * The IASIOs in input to the ASCE.
	 * 
	 * ManyToMany: the ASCE can have multiple IASIOs in input and the same IASIO can be 
	 * the input of many ASCEs
	 */
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinTable(name= "ASCE_IASIO",
	joinColumns = @JoinColumn(name="asce_id"),
	inverseJoinColumns = @JoinColumn(name = "io_id"))
    private Map<String, IasioDao> inputs = new HashMap<>();
	
	/**
	 * The output generated by the ASCE applying the TF to the inputs
	 */
	@OneToOne
    @JoinColumn(name = "OUTPUT_ID")
	private IasioDao output;
	
	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
	@JoinTable(name= "ASCE_PROPERTY",
		joinColumns = @JoinColumn(name="asce_id"),
		inverseJoinColumns = @JoinColumn(name = "props_id"))
	private Set<PropertyDao> props = new HashSet<>();
	
	public AsceDao() {}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		Objects.requireNonNull(id,"The ASCE ID can't be null");
		String iden = id.trim();
		if (iden.isEmpty()) {
			throw new IllegalArgumentException("The ASCE ID can't be an empty string");
		}
		this.id = iden;
	}

	public String getTfClass() {
		return tfClass;
	}

	public void setTfClass(String tfClass) {
		Objects.requireNonNull(tfClass,"The TF class of a ASCE can't be null");
		String temp = tfClass.trim();
		if (temp.isEmpty()) {
			throw new IllegalArgumentException("The TF class of a ASCE can't be an empty string");
		}
		this.tfClass = temp;
	}

	public IasioDao getOutput() {
		return output;
	}

	public Collection<IasioDao> getInputs() {
		return inputs.values();
	}
	
	/**
	 * Put the passed input in the map of inputs.
	 * 
	 * @param i The IASIO to put in the map
	 * @param replace If <code>true</code> replaces the old IASIO with
	 *                this one, if already present in the map
	 * @return <code>true</code> the previous value associated to the key in the map,
	 *         or <code>null</code> if the key was not in the map
	 */
	public IasioDao addInput(IasioDao i, boolean replace) {
		Objects.requireNonNull(i, "Can't add a null IASIO");
		if (!inputs.containsKey(i.getId())) {
			return inputs.put(i.getId(),i);
		} else {
			if (!replace) {
				return null;
			}
			return inputs.put(i.getId(),i);
		}
	}
	
	public void setOutput(IasioDao output) {
		Objects.requireNonNull(output,"The output of a ASCE can't be null");
		this.output = output;
	}

	public Set<PropertyDao> getProps() {
		return props;
	}
	
	public void setDasu(DasuDao dasu) {
		this.dasu=dasu;
	}

	public DasuDao getDasu() {
		return dasu;
	}
	
	/**
	 * </code>toString()</code> prints a human readable version of the ASCE
	 * where linked objects (like DASU, IASIOS..) are represented by their
	 * IDs only.
	 */
	@Override
	public String toString() {
		StringBuilder ret = new StringBuilder("ASCE=[ID=");
		ret.append(id);
		ret.append(", Output=");
		Optional.ofNullable(output).ifPresent(x -> ret.append(x));
		ret.append(", Inputs={");
		for (IasioDao iasio: getInputs()) {
			ret.append(' ');
			ret.append(iasio.getId());
		}
		ret.append("}, TF class=");
		ret.append(tfClass);
		ret.append(", DASU=");
		Optional.ofNullable(dasu).ifPresent(x -> ret.append(x.getId()));
		ret.append(", Props={");
		for (PropertyDao prop: props) {
			ret.append(' ');
			ret.append(prop.toString());
		}
		ret.append("}]");
		return ret.toString();
	}

	/**
	 * <code>hashCode</code> evaluates the code by the members of this object
	 * but the replacing the included DASU and IASIOs with their IDs.
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dasu == null) ? 0 : dasu.getId().hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((inputs == null) ? 0 : inputs.keySet().hashCode());
		result = prime * result + ((output == null) ? 0 : output.getId().hashCode());
		result = prime * result + ((props == null) ? 0 : props.hashCode());
		result = prime * result + ((tfClass == null) ? 0 : tfClass.hashCode());
		return result;
	}

	/**
	 * <code>equals</code> check the equality of the members of this object
	 * against the one passed in the command line but the checking of included
	 * DASU, and IASIOs is limited to their IDs.
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AsceDao other = (AsceDao) obj;
		if (dasu == null) {
			if (other.dasu != null)
				return false;
		} else if (!dasu.getId().equals(other.dasu.getId()))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (inputs == null) {
			if (other.inputs != null)
				return false;
		} else if (!inputs.keySet().equals(other.inputs.keySet()))
			return false;
		if (output == null) {
			if (other.output != null)
				return false;
		} else if (!output.getId().equals(other.output.getId()))
			return false;
		if (props == null) {
			if (other.props != null)
				return false;
		} else if (!props.equals(other.props))
			return false;
		if (tfClass == null) {
			if (other.tfClass != null)
				return false;
		} else if (!tfClass.equals(other.tfClass))
			return false;
		return true;
	}
	
}
