pipeline {
    agent any

    
    triggers {
        // Run once per day at 03:00 (server time)
        cron('0 3 * * *')
    }

    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    
    environment {
        // Define your environment variables here
        //GRADLE_HOME = '/path/to/gradle'
        //JAVA_HOME = '/path/to/java'
        PATH = "${env.PATH}:/var/lib/jenkins/.local/bin"
        IAS_ROOT = "${env.WORKSPACE}/IasRoot"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Create Folders') {
            steps {
                sh 'mkdir -p IasRoot'
                sh 'mkdir -p ias'
            }
        }

        stage('Checkout') {
            steps {
                dir('ias') {
                  // Uses the SCM defined by the multibranch job (including branch, commit, and credentials)
                  checkout scm
                }
            }
        }
        stage('Setup Python Env') {
            steps {
                sh '''
                set -e
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r ias/JenkinsFiles/python-requirements.txt
                '''
            }
        }
        stage('Build') {
            steps {
                dir('ias') {
                    sh '''
                      set -e
                      . ../venv/bin/activate
                      ./gradlew clean build
                    '''
                }
            }
        }
        stage('Install') {
            steps {
                dir('ias') {
                    sh '''
                      set -e
                      . ../venv/bin/activate
                      ./gradlew install
                    '''
                }
            }
        }
        stage('Compress IasRoot') {
            steps {
                sh 'tar -czf IasRoot.tgz -C IasRoot .'
            }
        }
        stage('Compress ias') {
            steps {
                sh '''
                    tar -czf ias.tgz --exclude='build' --exclude='*/build' --exclude='*.log' -C ias .
                '''
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/*.tgz'
            build job: 'IAS-IntegrationTest', wait: false, parameters: [
                string(name: 'BRANCH_NAME', value: env.BRANCH_NAME)
              ]
        }
        
        always {
            junit '**/build/test-results/**/*.xml'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
