pipeline {
    agent any

    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    
    environment {
        // Define your environment variables here
        //GRADLE_HOME = '/path/to/gradle'
        //JAVA_HOME = '/path/to/java'
        PATH = "${env.PATH}:/var/lib/jenkins/.local/bin"
        IAS_ROOT = "${env.WORKSPACE}/IasRoot"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Create Folders') {
            steps {
                sh 'mkdir -p IasRoot'
                sh 'mkdir -p ias'
            }
        }

        stage('Checkout') {
            steps {
                dir('ias') {
                  // Uses the SCM defined by the multibranch job (including branch, commit, and credentials)
                  checkout scm
                }
            }
        }
        stage('Setup Python Env') {
            steps {
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r ias/JenkinsFiles/python-requirements.txt
                '''
            }
        }
        stage('Build') {
            steps {
                dir('ias') {
                    sh '''
                      set -e
                      . ../venv/bin/activate
                      ./gradlew build
                    '''
                }
            }
        }
        stage('Install') {
            steps {
                dir('ias') {
                    sh '''
                      set -e
                      . ../venv/bin/activate
                      ./gradlew install
                    '''
                }
            }
        }
        stage('Compress IasRoot') {
            steps {
                sh 'tar -czf IasRoot.tgz -C IasRoot .'
            }
        }
        stage('Compress ias') {
            steps {
                sh 'tar -czf ias.tgz -C ias .'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/*.tgz'
            build job: 'MasterUnitTest', wait: false

        }
    }
}
