name: code-check
run-name: ${{ github.actor }} check IAS code quality
on: [push]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - name: Checkout IAS code
        uses: actions/checkout@v3
      - run: python -V
      - run: java -version
      - run: mkdir IasRoot
      - name: Build with gradlew
        run: ./gradlew build
        env:
          IAS_ROOT: IasRoot

