name: code-check
run-name: ${{ github.actor }} check IAS code quality
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/IasRoot'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - name: Checkout IAS code
        uses: actions/checkout@v3
      - run: git status
      - run: pwd
      - run: python -V
      - run: java -version
      - run: mkdir $IAS_ROOT
      - name: Build IAS with gradlew
        run: ./gradlew build
      - name: Install IAS in IAS_ROOT
        run: ./gradlew install
      - run: ls -R $IAS_ROOT
      - run: ls -R BasicTypes/build

