name: ias-build-install
run-name: ${{ github.actor }} Build IAS
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/ias/IasRoot'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    outputs:
      ias_root_path: ${{ steps.set-env.outputs.IAS_ROOT }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - run: python -V
      - name: Install PySide6
        run: pip install PySide6
      - run: java -version
      - run: mkdir $IAS_ROOT
      - name: Checkout IAS code
        uses: actions/checkout@v4
        with:
          path: GIT
      - run: ls
      - name: Clean
        run: |
          cd GIT
          ./gradlew clean
      - name: Build IAS with gradlew
        run: |
          cd GIT
          ./gradlew build
      - name: Install IAS in IAS_ROOT
        run: |
          cd GIT
          ./gradlew install
      - name: List IAS_ROOT content
        run: ls -lR $IAS_ROOT
      - name: Create a tar archive of IAS_ROOT with preserved attributes
        run: tar -cvzf ias-root.tgz IasRoot
      - uses: actions/upload-artifact@v4
        with:
          name: ias-root.tgz
          path: ias-root.tgz
          retention-days: 7
          include-hidden-files: true
  unit-tests:
    needs: Build-IAS
    runs-on: ubuntu-latest
    env:
      IAS_ROOT: '/home/runner/work/ias/ias/IasRoot'
      GITHUB_WORKSPACE: '/home/runner/work/ias/ias/GIT'
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - run: echo "Using IAS_ROOT $IAS_ROOT"
      - name: Install PySide6
        run: pip install PySide6
      - name: Install jep
        run: pip install jep
      - name: Install python dateutil
        run: pip install python-dateutil
      - name: Download IAS ROOT
        uses: actions/download-artifact@v4
        with:
          name: ias-root.tgz
          path: ./
      - run: ls -la
      - name: Extract tar with IAS_ROOT
        run: tar xvzf ias-root.tgz
      - run: ls -la
      - name: Checkout IAS code
        uses: actions/checkout@v4
        with:
          path: GIT
      - run: ls -la
      - name: Clean
        run: |
          cd GIT
          ./gradlew clean
      - name: Build IAS with gradlew
        run: |
          cd GIT
          ./gradlew build
      - name: Run unit tests
        run: |
          cd GIT
          . Tools/config/ias-bash-profile.sh
          python3 -V
          env
          ./gradlew iasUnitTest 2>&1 >unit-tests.out
      - uses: actions/upload-artifact@v4
        with:
          name: unit-tests.out
          path: unit-tests.out
          retention-days: 15
          include-hidden-files: true
