name: ias-build-test-install
run-name: ${{ github.actor }} Build IAS
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/ias/IasRoot'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    outputs:
      ias_root_path: ${{ steps.set-env.outputs.IAS_ROOT }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java
        run: |
          echo JAVA_HOME=$JAVA_HOME
          ls $JAVA_HOME/lib/server
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python --version
      - name: Install python tools
        run: |
          pip install --upgrade pip
          pip install PySide6 jep python-dateutil pytest confluent-kafka PyYAML
      - run: java -version
      - run: mkdir -p $IAS_ROOT
      - name: Checkout IAS code
        uses: actions/checkout@v4
        with:
          path: GIT
      - run: ls
      - name: Clean
        working-directory: GIT
        run: ./gradlew clean
      - name: Build the IAS and run unit tests with gradlew
        env:
          JEP_JVM: ${{ env.JAVA_HOME }}/lib/server/libjvm.so          
        working-directory: GIT
        run: ./gradlew build
      - name: Install IAS in IAS_ROOT
        working-directory: GIT
        run: ./gradlew install
      - name: List IAS_ROOT content
        run: ls -lR $IAS_ROOT
      - name: Create a tar archive of IAS_ROOT with preserved attributes
        run: tar -cvzf ias-root.tgz -C "$(dirname "$IAS_ROOT")" "$(basename "$IAS_ROOT")"
      - name: Upload IAS_ROOT tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ias-root.tgz
          path: ias-root.tgz
          retention-days: 7
          include-hidden-files: true
      - name: Upload unit tests output
        uses: actions/upload-artifact@v4
        if: always()   # ensures upload even if tests fail
        with:
          name: unit-test-results
          path: $GITHUB_WORKSPACE/**/*.xml
          retention-days: 7
          include-hidden-files: true
      - name: Export IAS_ROOT as step output
        id: export
        run: echo "IAS_ROOT=$IAS_ROOT" >> "$GITHUB_OUTPUT"

