name: ias-build-install
run-name: ${{ github.actor }} Build IAS
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/IasRoot'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Checkout IAS code
        uses: actions/checkout@v4
      - name: Install PySide6
        run: pip install PySide6
      - run: git status
      - run: pwd
      - run: python -V
      - run: java -version
      - run: mkdir $IAS_ROOT
      - run: rm -rf $IAS_ROOT/*
      - name: Clean
        run: ./gradlew clean
      - name: Build IAS with gradlew
        run: ./gradlew build
      - name: Install IAS in IAS_ROOT
        run: ./gradlew install
      - name: Create IasRoot artifact
        working-directory: /home/runner/work
        run: |
          ls
          tar czf IasRoot.tgz IasRoot
      - name: Upload IasRoot artifact
        uses: actions/upload-artifact@v4
        with:
          name: IasRoot
          path: $IAS_ROOT
          if-no-files-found: error
