name: ias-build-install
run-name: ${{ github.actor }} Build IAS
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/IasRoot'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - name: Checkout IAS code
        uses: actions/checkout@v3
      - name: Install PySide6
        run: pip install PySide6
      - run: git status
      - run: pwd
      - run: python -V
      - run: java -version
      - run: mkdir $IAS_ROOT
      - run: rm -rf $IAS_ROOT/*
      - name: Clean
        run: ./gradlew clean
      - name: Build IAS with gradlew
        run: ./gradlew build
      - name: Install IAS in IAS_ROOT
        run: ./gradlew install
      - name: List IAS_ROOT content
        run: ls -lR $IAS_ROOT
      - name: Create IAS root tar file
        run: tar czf /home/runner/work/ias/IasRoot.tgz $IAS_ROOT
      - uses: actions/upload-artifact@v4
        with:
          name: IasRoot
          path: $IAS_ROOT
          retention-days: 30
          include-hidden-files: true
