name: ias-build-install
run-name: ${{ github.actor }} Build IAS
on: [push]
env:
  IAS_ROOT: '/home/runner/work/ias/ias/IasRoot'
  GITHUB_WORKSPACE: '/home/runner/work/ias/ias/GIT'
jobs:
  Build-IAS:
    runs-on: ubuntu-latest
    outputs:
      ias_root_path: ${{ steps.set-env.outputs.IAS_ROOT }}
      ias_github_path: ${{ steps.set-env.outputs.GITHUB_WORKSPACE }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - run: python -V
      - name: Install PySide6
        run: pip install PySide6
      - run: java -version
      - run: mkdir $IAS_ROOT
      - run: mkdir GITHUB_WORKSPACE
      - name: Checkout IAS code
        uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE
      - name: Clean
        run: ./gradlew clean
      - name: Build IAS with gradlew
        run: ./gradlew build
      - name: Install IAS in IAS_ROOT
        run: ./gradlew install
      - name: List IAS_ROOT content
        run: ls -lR $IAS_ROOT
      - uses: actions/upload-artifact@v4
        with:
          name: IasRoot
          path: IasRoot
          retention-days: 15
          include-hidden-files: true
  unit-tests:
    needs: Build-IAS
    runs-on: ubuntu-latest
    steps:
      - run: echo "Using IAS_ROOT ${{ needs.Build-IAS.outputs.ias_root_path }}"
      - run: echo "Using GITHUB_WORKSPACE ${{ needs.Build-IAS.outputs.ias_github_path }}"
      - run: env
      - run: pwd
      - name: Install PySide6
        run: pip install PySide6
      - name: Install jep
        run: pip install jep
      - run: ls -la
      - name: Download IAS ROOT
        uses: actions/download-artifact@v4
        with:
          name: IasRoot
          path: IasRoot
      - name: Checkout IAS code
        uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE
      - name: Clean
        run: ./gradlew clean
      - name: Build IAS with gradlew
        run: ./gradlew build
      - run: ls -l
      - run: ls -l IasRoot
